spring:
  data:
    mongodb:
#      host: mongodb
#      port: 27017
#      database: MCQ
#      username: admin
#      password: admin
      uri: "mongodb://admin:admin@localhost:27017/MCQ?authSource=admin"
  application:
    name: mcqQuestions

application:
  version: 0.0.1-SNAPSHOT
  #      jwtProperties:
  #          key: this_is_really_a_strong_private_key_which_can_not_be_cracked_by_any_psycho_programmer
  #          alg: HS512
  #          sub: JWT
  #          iss: iss
  #          clientCodes: apigee-proxy-service,apigee-proxy-service
  cors:
    allowed-origins: "*"
    allowed-methods: "*"
    allowed-headers: "*"
    exposed-headers: "Authorization,Link,X-Total-Count"
    allow-credentials: true
    max-age: 1800
    path: "/**"

management:
  endpoints:
    web:
      exposure:
        include=*
    shutdown:
      enabled=true

endpoints:
  shutdown:
    enabled=true

server:
  port: 8102
  servlet:
    context-path: /questions
  host-address: localhost

logging:
  config: classpath:logback-spring.xml
  level:
    root: INFO