version: "3.3"
services:
  quiz-mongodb:
    platform: linux/amd64
    container_name: quiz-mongodb
    volumes:
      - "mongodb_data_container:/data/db"
      - "./mongo-seed:/mongo-seed"
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=admin
    networks:
      mcq:
        ipv4_address: 172.16.0.1
    command: mongod --bind_ip 127.0.0.1,172.16.0.1
    image: mongo:latest
    env_file:
      - .env
  quizzes:
    platform: linux/amd64
    privileged: true
    volumes:
      - .:/app"
    image: alesharay100/quizzes:v1.0
    ports:
      - "8102:8102"
    networks:
      mcq:
    depends_on:
      - quiz-mongodb
    env_file:
      - .env
    links:
      - quiz-mongodb

networks:
  mcq:
    driver: bridge
    ipam:
      config:
        - subnet: 172.16.0.0/24
          gateway: 172.16.0.254

volumes:
  mongodb_data_container:
    external: false
